
(define-module (helm tyk-helm tyk-single-dc)
  #:use-module (guix utils)
  #:use-module (guix gexp)
  #:use-module (guix build utils)
  #:use-module (json)
  #:use-module (gnu packages base)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system copy))


(define-public tyk-single-dc-1.0.0-beta7
  (package
   (name "tyk-single-dc")
   (version "1.0.0-beta7")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-single-dc-1.0.0-beta7.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying Tyk Self Managed stack on a cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file. It includes: Tyk Gateway, an open source Enterprise API Gateway (supporting REST, GraphQL, TCP and gRPC protocols). Tyk Pump, an analytics purger that moves the data generated by your Tyk nodes to any back-end. Tyk Dashboard, a license based component that provides GUI management interface and analytics platform for Tyk. Tyk Developer Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.  This chart has been deprecated. Please use tyk-stack chart instead.")
   (description "A Helm chart for deploying Tyk Self Managed stack on a cluster. It will deploy all required Tyk components with the settings provided in the values.yaml file. It includes: Tyk Gateway, an open source Enterprise API Gateway (supporting REST, GraphQL, TCP and gRPC protocols). Tyk Pump, an analytics purger that moves the data generated by your Tyk nodes to any back-end. Tyk Dashboard, a license based component that provides GUI management interface and analytics platform for Tyk. Tyk Developer Enterprise Portal, a full-fledged CMS-like system for API providers to publish, monetise and drive the adoption of APIs.  This chart has been deprecated. Please use tyk-stack chart instead.")
   (license #f)))

(define-public tyk-single-dc-1.0.0-beta6
  (package
   (name "tyk-single-dc")
   (version "1.0.0-beta6")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-single-dc-1.0.0-beta6.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (description "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (license #f)))

(define-public tyk-single-dc-1.0.0-beta5
  (package
   (name "tyk-single-dc")
   (version "1.0.0-beta5")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-single-dc-1.0.0-beta5.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (description "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (license #f)))

(define-public tyk-single-dc-1.0.0-beta4
  (package
   (name "tyk-single-dc")
   (version "1.0.0-beta4")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-single-dc-1.0.0-beta4.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (description "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (license #f)))

(define-public tyk-single-dc-1.0.0-beta3
  (package
   (name "tyk-single-dc")
   (version "1.0.0-beta3")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-single-dc-1.0.0-beta3.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (description "A Helm chart for deploying an instance of Tyk Single Datacenter composed of Tyk Gateway, Tyk Pump and Tyk Dashboard")
   (license #f)))