
(define-module (helm tyk-helm tyk-mdcb-data-plane)
  #:use-module (guix utils)
  #:use-module (guix gexp)
  #:use-module (guix build utils)
  #:use-module (json)
  #:use-module (gnu packages base)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system copy))


(define-public tyk-mdcb-data-plane-1.1.0
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.1.0")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.1.0.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploying a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end. Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.  This chart has been deprecated. Please use tyk-data-plane chart instead.")
   (description "A Helm chart for deploying a Tyk data plane for Tyk Self Managed MDCB or Tyk Cloud users. It will deploy the data plane components that remotely connect to a MDCB control plane. It includes the Tyk Gateway, an open source Enterprise API Gateway, supporting REST, GraphQL, TCP and gRPC protocols; and Tyk Pump, an analytics purger that moves the data generated by your Tyk gateways to any back-end. Furthermore, it has all the required modifications to easily connect to Tyk Cloud or Multi Data Center (MDCB) control plane.  This chart has been deprecated. Please use tyk-data-plane chart instead.")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (description "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta6
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta6")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta6.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (description "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta5
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta5")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta5.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (description "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta4
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta4")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta4.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (description "A Helm chart for deploy a Tyk Multi Data Center Bridge composed on Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta3
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta3")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta3.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for Kubernetes")
   (description "A Helm chart for Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta2
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta2")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta2.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for Kubernetes")
   (description "A Helm chart for Kubernetes")
   (license #f)))

(define-public tyk-mdcb-data-plane-1.0.0-beta1
  (package
   (name "tyk-mdcb-data-plane")
   (version "1.0.0-beta1")
   (source (origin
            (method url-fetch)
            (uri "https://helm.tyk.io/public/helm/charts/tyk-mdcb-data-plane-1.0.0-beta1.tgz")
            (sha256 #f)))
   (build-system copy-build-system)
   (home-page "")
   (synopsis "A Helm chart for Kubernetes")
   (description "A Helm chart for Kubernetes")
   (license #f)))